import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const apiKey = process.env.CoreTiny_API_KEY;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head>
        <script src={`https://cdn.tiny.cloud/1/${apiKey}/tinymce/5/tinymce.min.js`} referrerPolicy="origin"></script>
      </head>
      <body >{children}</body>
    </html>
  )
}
